### ISSUE TITLE
arcon Rust API

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#108]
As we were talking about adding a Rust API for arcon, I thought it would be good to discuss some possible options:

Using a builder API on top of ``ArconPipeline``

```rust
let mut pipeline = ArconPipeline::new();
pipeline.source(...)
  .map(|x|  x + 10)
  .sink(...)
```

Others?

**Comment by Bathtor** [comment]
I think one thing we gotta think about is what parts we will still want to compile (e.g., via macros) and which parts we can just generate dynamically from some kind builder API like the one you described. And perhaps how to interlink with custom handwritten code (i.e., `.operator(my_custom_operator)` in the builder).

**Comment by frej** [comment]
Wouldn't it be nice to package arcscript-defined operators in a crate and then let the arcon runtime/compiler make sure it gets linked or inlined where it makes sense?

**Comment by Max-Meldrum** [comment]
> Wouldn't it be nice to package arcscript-defined operators in a crate and then let the arcon runtime/compiler make sure it gets linked or inlined where it makes sense?

yeah, sounds like a good approach. But that is more related to the codegen part of arcon and not the Rust API.

**Comment by Max-Meldrum** [comment]
Just adding some notes / high-level sketch of a possible implementation...

```rust
let pipeline = Pipeline::new();
pipeline.from_collection(...) -> Stream<ArconType> {}
```

Allow users to perform transformations using a ``Stream`` object.  Enough information should be added to an underlying dataflow graph builder so that in the end we can use this to build the pipeline.

```rust
pub struct Stream<IN: ArconType> {
    dataflow_graph: Graph<...>,
    id: ...
}

impl<IN: ArconType> Stream<IN> {
    // pre-defined operators
    pub fn map<OUT: ArconType, F: Fn(IN) -> ArconResult<OUT>>(&mut self, f: F) -> Stream<OUT> {}
    pub fn map_with_state<OUT, S, F>(&mut self, f: F) -> Stream<OUT>
    where 
          OUT: ArconType,
          S: ArconState,
          F:  Fn(IN, &mut S) -> ArconResult<OUT>,
    {
    }
    // custom operator
    pub fn operator<OUT: ArconType>(&mut self, operator: impl Operator) -> Stream<OUT> {}
}
```

**Comment by segeljakt** [comment]
I like the approach. I don't know if it's possible but could you also have custom sources and sinks?
```rust
pub fn sink(&mut self, operator: impl Operator) {}
pub fn source<OUT: ArconType>(operator: impl Operator) -> Stream<OUT> {}
```

**Comment by Max-Meldrum** [comment]
> I like the approach. I don't know if it's possible but could you also have custom sources and sinks?
> 
> ```rust
> pub fn sink(&mut self, operator: impl Operator) {}
> pub fn source<OUT: ArconType>(operator: impl Operator) -> Stream<OUT> {}
> ```

Yes, should be possible to fix.

**Comment by segeljakt** [comment]
I'm wondering, if you want to run multiple pipelines which are not connected, can you run them in the same Arcon instance or do you need to spawn one Arcon instance per pipeline?

```rust
let mut arcon = Arcon::new();
let pipeline_foo = Pipeline::new();
let pipeline_bar = Pipeline::new();
...
arcon.register(pipeline_foo);
arcon.register(pipeline_bar);
```

**Comment by Max-Meldrum** [comment]
Each pipeline has its own configuration, allocator, scheduler etc.. So I think the first approach you described could be a good one.

**Comment by segeljakt** [comment]
If the first one is possible, can we access the Arcon object from within operators to spawn pipelines dynamically?

**Comment by Max-Meldrum** [comment]
> If the first one is possible, can we access the Arcon object from within operators to spawn pipelines dynamically?

Should be possible. Either through accessing an ``Arc<Arcon>`` object through the OperatorContext or simply just adding the ``Arc<Arcon>`` to the custom operator.

**Comment by segeljakt** [comment]
This might be one way of representing the graphs:
```rust
pub struct Stream<IN: ArconType> {
    // TODO: add vec/graph to hold information of current "pipeline"
    _marker: PhantomData<IN>,
    /// fiz ----------\
    /// foo -> bar -> baz
    ///     \-------> qux
    /// Example:
    /// graphs = {
    ///   fiz <- []
    ///   foo <- []
    ///   baz <- [bar, fiz]
    ///   bar <- [foo]
    ///   qux <- [foo]
    /// }
    graph: HashMap<NodeId, Vec<NodeId>>,
    info: HashMap<NodeId, DfgNode>,
}
```
Maybe we could have a node type:
```rust
pub struct Stream<IN: ArconType> {
    // TODO: add vec/graph to hold information of current "pipeline"
    _marker: PhantomData<IN>,
    graph: HashMap<NodeId, Node>,
}
pub struct Node {
    ingoing: Vec<NodeId>,
    ....
}
```

**Comment by segeljakt** [comment]
These are some options for how to represent configurations:

# Option 1:

```rust
foo.map(|x| x + 1)
   .with_backend(Backend::Rocks)
   .with_name("foo")
   .filter(|x| x != 0)
```

# Option 2:

```rust
foo.map_with_conf(|x| x + 1, |conf|
       conf.with_backend(Backend::Rocks)
       conf.with_name("foo")
    )
   .filter(|x| x != 0)
```

# Option 3:

```rust
foo.map_with_conf(|x| x + 1, Conf::new()
       .with_backend(Backend::Rocks)
       .with_name("foo")
    )
   .filter(|x| x != 0)
```

# Option 4:

```rust
foo.map(|x| x + 1)
   .with_conf(|conf|
       conf.with_backend(Backend::Rocks)
       conf.with_name("foo")
    )
   .filter(|x| x != 0)
```

# Option 5:

```rust
foo.map(|x| x + 1)
   .with_conf(Conf::new()
       .with_backend(Backend::Rocks)
       .with_name("foo")
    )
   .filter(|x| x != 0)
```

**Comment by Bathtor** [comment]
You could also *always* expect a configuration instead of having special methods for when you want one, and then have a trivial configuration available. It's sometimes a bit of a pity, that Rust doesn't have optional named parameters, though :(

Apart from that, I do still like Option 2 the best, because a) it keeps the pipeline flat and b) it allows you to have different conf types for each operator (assuming different operators allow different configuration options) without the user having to learn all of their type names, as the compiler will just infer the actual type for the closure.

Although 2 and 4 need braces and semicolons, which makes them a bit more verbose.

But maybe we shouldn't spend so much time obsessing over this, seeing as this will not be primary user facing API for the system :D

**Comment by segeljakt** [comment]
```rust
foo.map((|x| x + 1)
        .with_backend(Backend::Rocks)
        .with_name("foo")
    )
   .filter(|x| x != 0)
```
🤣

**Comment by Max-Meldrum** [comment]
#139 added the initial API.  It is not complete but as it fulfills the objectives of the 0.2.0 milestone, I'll close this and new issues regarding the API can be opened.
