### ISSUE TITLE
Disable RocksDB WAL 

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#112]
The write-ahead log is enabled by default ( https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log). I am 99% sure that we do not need it on as we operate within epochs. That is, we have the truth from the latest epoch checkpoint.

**Comment by mrobakowski** [comment]
Good catch! Can you assign me to this issue? The same is probably also the case for other backends, so I'll check them as well.
