### ISSUE TITLE
add SQL layer

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#134]
Let's say we have this data in Arcon. 
```rust
#[cfg_attr(feature = "arcon_serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Arcon, prost::Message, Clone, abomonation_derive::Abomonation)]
#[arcon(unsafe_ser_id = 12, reliable_ser_id = 13, version = 1)]
pub struct MyData {
   #[prost(uint32, tag = "1")]
   pub id: u32,
}
```
Then it would be nice to be able to run basic SQL queries against the data.

Look into how to use [sqlparser](https://github.com/ballista-compute/sqlparser-rs) and run a simple query like this on top of our state backends.

```rust
let sql = "SELECT id FROM mydata;"

```

Good starting point:  https://github.com/cswinter/LocustDB  uses ``sqlparser`` to run queries on data from RocksDB.

**Comment by segeljakt** [comment]
I took a look and it seems like they execute the parsed queries in this file https://github.com/cswinter/LocustDB/blob/3a180e58446d263dee73023275946ebdd6b16081/src/engine/execution/query_task.rs. Do we implement a module which executes the SQL-AST from `sqlparser` by interpreting it in terms of operations exposed by RocksDB and Sled, or do you think we can reuse someones solution?

**Comment by Max-Meldrum** [comment]
I was thinking it would be nice to have it execute on top of our existing ``Backend`` implementation so that it wouldn't matter if the ``Backend``is Sled or RocksDB etc...

But yeah, would perhaps need to use someones implementation as template.

**Comment by Max-Meldrum** [comment]
Closing this as we are going for Arrow #150
