### ISSUE TITLE
Add support for startup methods in operators

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arcon#159]
Some operators may need to run startup code which has access to the `OperatorContext` before they begin to handle elements. For example, tumbling window operators might need to schedule a timer. Would it be possible to support an optional startup-method such as the following?

```rust
trait Operator {
    // ...
    fn startup(&mut self, mut ctx: OperatorContext<Self, impl Backend, impl ComponentDefinition>) -> OperatorResult<()> {
        Ok(())
    }
    // ...
}
```

If it is, then it could be a good first issue.

**Comment by Max-Meldrum** [comment]
Yes, sounds like a good thing to add.  It just needs to be added in the trait as you showed. And then also it needs to be called within the Node component.  Would prefer to follow similar naming scheme as Kompact with ``on_start`` and later on we perhaps need an ``on_recovery`` too.
