### ISSUE TITLE
Time helper methods

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#162]
Add some time methods to make it easier when creating windows etc...

```rust
// src/stream/time/mod.rs
pub struct Time(u64);

impl Time {
 pub fn seconds(seconds: usize) -> Self { 
    // no need to convert...    
 }
 pub fn minutes(minutes: usize) -> Self {
    // convert to seconds
 }
 pub fn hours(hours: usize) -> Self {
    // convert to seconds
 }
 pub fn days(days: usize) -> Self {     
    // convert to seconds
 }
}
```

So rather than writing the seconds manually like this:

```rust
WindowAssigner::sliding(function, backend, 1000, 500, 0, false)
```

Use the time utility (just random values..):

```rust
WindowAssigner::sliding(function, backend, Time::hours(1), Time::hours(2), Time::minutes(10), false)
```

**Comment by segeljakt** [comment]
Would it be possible/sensible to also support std::time::Duration?

**Comment by Max-Meldrum** [comment]
Yes, could have a method that takes a Duration as well. This is just for windowing logic and as we rely on it being seconds. Should be fine as there is ``Duration::as_secs()`` if I recall correctly.

Lars recommended the ``uom`` crate where you can write things like 
```rust
1000.seconds();
1000.5.seconds();
```
But as we just want to convert to seconds, might be better with the Time struct solution. But could be worth to implement ``uom``stuff for our Arcon types.
