### ISSUE TITLE
Proc macro for deriving protobuf bloat code

### ISSUE THREAD

**Issue by segeljakt** [cda-group/arcon#164]
A copy of the `#[macros::proto]` macro in https://github.com/Max-Meldrum/arcon_taxi/tree/main/macros/src currently sits in the arc-script repo, but would you be interested in moving it to the arcon repo?

I think there is a lot of potential for using proc macros to automatically integrate Arcon with other tools. For example, it should be possible to derive a method for a data type which uploads a schema of that data type to Kibana, and also a function for uploading events of the schema.

**Comment by Max-Meldrum** [comment]
Yes, I think that would be a nice addition! 

So I guess if it goes in  ``arcon_macros/``, one could use ``[arcon_macros::proto]``?

**Comment by segeljakt** [comment]
sounds good 👍
