### ISSUE TITLE
Iterator interface for Sources

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#182]

**Comment by segeljakt** [comment]
Related docs (`std::stream`): https://doc.rust-lang.org/std/stream/index.html

The API we discussed might look like this if I understood:

```rust
trait Source {
    type Item;
    // Get next element
    fn poll_next(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Self::Item>>;
    // Restart source at offset 0.
    fn restart(self: Pin<&mut Self>);
    // Configure offset (fast-forward or rewind?)
    fn set_offset(self: Pin<&mut Self>, offset: usize);
}
```

**Comment by Bathtor** [comment]
Yeah, though I guess with some specialisations. As in, `set_offset` is probably optional but if it is provided then `restart` is just `set_offset(0)`.
