### ISSUE TITLE
checkpoints directory not getting created automtically if not present while using the Rocks backend

### ISSUE THREAD

**Issue by Sanskar95** [cda-group/arcon#252]

**Comment by Max-Meldrum** [comment]
The error message:

``ERRO Failed to handle message: Unexpected bug RocksError: IO error: No such file or directory: While mkdir: /tmp/arcon/app_1/checkpoints/ClickState_0/checkpoint_ClickState_0_0.tmp: No such file or directory please report at https://github.com/cda-group/arcon, location: src/stream/node/mod.rs:758``
