### ISSUE TITLE
Improve test cases and error handling

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#39]
* Do create_and_register instead and wait for callback instead of sleeping the thread.
* Add more error logging (mostly tokio)

**Comment by Bathtor** [comment]
I'm actually also having open file issues with my benchmark suite now. I wonder if something changed there recently in Rust, MacOS or just Tokio, that suddenly makes this an issue...

**Comment by Max-Meldrum** [comment]
Not relevant any longer. closing.
