### ISSUE TITLE
Fix socket tests for OSX

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#40]
Opening too many files for OSX to handle....

**Comment by Bathtor** [comment]
I feel it's probably more of a case of not closing things properly when you are done with them.
I checked on my system and the open fd limits is very low at 256, but still...running tests in sequence should not go over that, and yet it does on my system at least. So something's fishy there...

**Comment by Max-Meldrum** [comment]
We might be setting the KompactConfig with a default NetworkConfig in some places where it is actually not needed. But still, the amount of sockets we utilise during the tests should still be under 15.

**Comment by Max-Meldrum** [comment]
failing test fixed by #42 

The number of fds should be reduced at least a bit when tests are refactored in #39
