### ISSUE TITLE
Upgrade Tokio/Futures

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#41]
drop 0.1x

**Comment by Bathtor** [comment]
Maybe wait until `0.2` leaves alpha? Tokio difficult enough to work with as it is...don't really need to make your life worse with pre-releases...We should also try to keep kompact and arcon in sync there, so we don't unnecessarily build so many versions of tokio.

**Comment by Max-Meldrum** [comment]
Yeah, I agree. No rush here.

**Comment by Max-Meldrum** [comment]
closed by #65 

Multiple tokio builds should not be an issue as we are dropping tokio in Kompact in the coming future.
