### ISSUE TITLE
Arcon Default Binary Format

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#49]
With us moving away from the Weld runtime (#45), we will no longer be required to use Rust structs (although we could). We currently rely on Serde and Bincode to serialise our Rust structs into bytes so that they can be sent over the wire or stored in a state backend. However, I do not see this as a good approach moving forward. Why? Mainly two reasons: (1) lack of schema evolution; (2) performance reasons.

https://github.com/erickt/rust-serialization-benchmarks

**Note on Complexity** This is just based on my own experiences using the frameworks (In rust) on how complicated it would be to integrate them with Arcon.

| Framework       |  Schema Evolution  |  Performance |  Complexity |
| ------------- |-------------| -----| -----|
| Serde     | No | Medium  | Low
| Protobuf  | yes   |   Medium  | Medium
| Flatbuffers | yes   |    High  | High
| Cap’n Proto | yes   |   High | High

Both Flatbuffers and Cap'n Proto achieve similar performance due to not having any encode/decode step.

The point of this issue is to start a discussion.

**Comment by Max-Meldrum** [comment]
So for point 1. It would basically be something like [abomonation](https://github.com/TimelyDataflow/abomonation)?

**Comment by Bathtor** [comment]
> So for point 1. It would basically be something like [abomonation](https://github.com/TimelyDataflow/abomonation)?

I utterly hate to say it, but yeah...that's kinda what I was thinking...damn Frank McSherry for inspiring those terrible thoughts.

**Comment by Bathtor** [comment]
Can you also write what the serialise space usage of each of the methods is, please?

**Comment by Max-Meldrum** [comment]
| Framework       |  Small |  Large | 
| ------------- |-------------| -----|
| Protobuf  | 14 bytes   |   106 bytes
| Serde::Bincode   | 20 bytes | 228 bytes
| Abomonation | 24 bytes | 280 bytes

**Comment by Bathtor** [comment]
What about timing and size with compression? I saw you already had code for that...

**Comment by Max-Meldrum** [comment]
Updated previous posts :rocket:
