### ISSUE TITLE
Add config

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#71]
add some form of ArconConfig to configure batch size, batch timeouts, watermark interval etc....

**Comment by Bathtor** [comment]
I was planning to add this at Kompact level as well, at some point...We should probably coordinate, so we don't duplicate effort unnecessarily.

Was thinking to use [hocon](https://docs.rs/hocon/0.3.2/hocon), since it'll be the same format as Akka (Typesafe Config) configuration files.

**Comment by Bathtor** [comment]
How does https://github.com/kompics/kompact/blob/2f82b7d8e44dd71d8bca28b2b5a018a8d1779af0/core/src/lib.rs#L952 work for you?

**Comment by Max-Meldrum** [comment]
Would it be able to handle a file with both Arcon config and Kompact config? That is, will it panic if it sees something it does not understand?

**Comment by Bathtor** [comment]
It doesn't understand anything...It just loads stuff and makes it available to all components. Replacing `KompactConfig` internals with values from the config file I didn't implement, yet...later...maybe...not crucial right now, no?

**Comment by Max-Meldrum** [comment]
okay, well if it is the same as akka. Then it can be divided into kompact { .... } and arcon { .... }. Should be good.
:+1:
